name: SA
on:
  pull_request:
    branches:
      - master
jobs:
  analysis:
    name: Syntax Analysis
    runs-on: ubuntu-latest
    if: github.repository_owner == 'PreMiD'
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.BOT_KEY }}
          level: error
          reporter: github-pr-check
          filter_mode: file
          fail_on_error: true
          eslint_flags: ". --ext .ts"
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.BOT_KEY }}
